### ISSUE TITLE
Automating Creation of a new Java package

### ISSUE THREAD

**Issue by yeison** [rosjava/rosjava_core#164]
**The following steps will be wrapped up in package creation script in the near future.**

A promise that was made here:

https://github.com/rosjava/rosjava_core/blob/b2bcbbe14aaadbb1a81a07902ea7fd643fa2c63e/docs/src/main/sphinx/getting_started.rst

Anyway, I think that I can take this on myself.

**Comment by stonier** [comment]
We're merging in the catkinized rosjava_core and android_core forks from the ros-java organisation. They have already got some android create package scripts there, but are still missing these java create scripts. Since the build environment is different (CMakeLists.txt and package.xml) you might want to do this job there.

If you'd like to pursue this, the correct place is at https://github.com/rosjava/rosjava_tools.
