### ISSUE TITLE
Create anonymous node in rosjava

### ISSUE THREAD

**Issue by talregev** [rosjava/rosjava_core#208]
Here a link to simple ros node: [listener](http://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber%28python%29)

there is a way to create anonymous node:

``` python
    # In ROS, nodes are uniquely named. If two nodes with the same
    # node are launched, the previous one is kicked off. The
    # anonymous=True flag means that rospy will choose a unique
    # name for our 'listener' node so that multiple listeners can
    # run simultaneously.
    rospy.init_node('listener', anonymous=True)
```

How i can do the same functionality in rosjava?

Thanks,
Tal.

**Comment by stonier** [comment]
I haven't done it before, but I assume it would be when you write a class that extends `AbstractNodeMain`.

When you override `getDefaultNodeName`, instead of returning `Graphname` as some string, then use `GraphName.newAnonymous()` call. That'll just give you a prefix though, so you might want to concatenate it.

Code is in [GraphName.java](https://github.com/rosjava/rosjava_core/blob/indigo/rosjava/src/main/java/org/ros/namespace/GraphName.java).

**Comment by stonier** [comment]
Better place for questions is [ros answers](http://answers.ros.org/).

**Comment by talregev** [comment]
i will :+1: 
[Create anonymous node in rosjava](http://answers.ros.org/question/204972/create-anonymous-node-in-rosjava/)

**Comment by jubeira** [comment]
@talregev did the answer above work for you? can we close this one?

This could be somewhere in a tutorial, the question was indeed interesting.

**Comment by talregev** [comment]
Yes, you can close.
