### ISSUE TITLE
custom messages with fixed-length arrays is received in rosjava as an empty array

### ISSUE THREAD

**Issue by samuelba** [rosjava/rosjava_core#221]
I discovered an issue with messages containing an array with a fixed (predefined size). 

Message example that is not working:

```
string[5] names
```

Message example that is working:

```
string[] names
```

If I subscribe in rosjava (Android) to the first message, I always get an empty `names` array with size zero. However, if I publish the second message with dynamic size 5 (filled with `names.push_back("name");`) I get the correct size with the content.

Is this a known limitation? Or just a bug?

**Comment by adamantivm** [comment]
@samuelba sorry for such a late response but I am pretty sure this is a bug.
Today I submitted a fix for this that may be close to fixing what you reported.
I am closing this bug here as the other repo where you reported the issue (https://github.com/rosjava/rosjava_bootstrap/issues/520) is more appropriate.
